###########################################################
#   Description: Compile OpenWrt by GitHub Actions        #
#   Based on: https://github.com/P3TERX/Actions-OpenWrt   #
#   Author: Hyy2001X                                      #
###########################################################

name: x86_64

on:
  repository_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Comebac/86'
      
# 上面增加了触发启动项
  
  workflow_dispatch:
    inputs:
      DEFAULT_SOURCE:
        description: '编译源码'
        required: false
        default: '大雕-lede'
        type: choice
        options:
          - '大雕-lede'
          - '天灵-21.02'
          - '天灵-18.06-k5.4'
          - '天灵-18.06'
          - '天灵-master'
          - 'Lienol-21.02'
          - 'Lienol-19.07'
          - 'Lienol-master'
          - '官方-22.03'
          - '官方-21.02'
          - '官方-19.07'
          - '官方-master'
      Tempoary_CONFIG:
        description: '配置文件'
        required: false
        default: 'x86_64'
        type: choice
        options:
          - 'x86_64'
          - 'x86_64-AP'
          - '自定1'
          - '自定2'
      Tempoary_FLAG:
        description: '固件标签'
        default: '高大全(Full)'
        type: choice
        options:
          - '高大全(Full)'
          - '精简版(Simplify)'
          - '养老版(Ultrathin)'
      Tempoary_IP:
        description: '固件IP地址 [选填]'
        default: ''
      UPLOAD_RELEASES:
        description: '上传固件到 Github Releases'
        required: false
        default: 'true'
        type: boolean
      UPLOAD_ARTIFACTS:
        description: '上传固件到 Github Artifacts'
        required: false
        default: 'false'
        type: boolean
      CACHE_ACCELERATE:
        description: 'Cache 加速编译'
        required: false
        default: 'true'
        type: boolean
      DELETE_USELESS_FILES:
        description: '删除无用文件以增加编译空间'
        required: false
        default: 'false'
        type: boolean
      DELETE_OLD_WORKFLOW:
        description: '删除3天之前的所有Actions任务'
        required: false
        default: 'false'
        type: boolean
      SKIP_E5CPU:
        description: '跳过E5-CPU加速编译固件'
        required: false
        default: 'true'
        type: boolean
        
  schedule:
  - cron: 15 8 * * *
  
env:
  # 上传 bin 文件夹到 Github Artifacts
  UPLOAD_BIN_ARTIFACTS: false
  
  # 本仓库链接
  GIT_URL: https://github.com/${{github.repository}}
  
  # 本仓库帐号,比如 Hyy2001X
  GIT_ACTOR: ${{github.actor}}
  
  # 本仓库帐号、仓库，比如 Hyy2001X/AutoBuild-Actions-BETA,挂这里用有的,比如把很多东西写在AutoBuild_DiyScript.sh文件上有需要
  GIT_REPOSITORY: ${{github.repository}}
  
  # 本仓库密匙,挂这里用有的,比如把很多东西写在AutoBuild_DiyScript.sh文件上有需要
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  
  # 跳过E5CPU时候要一个触发文件,随便名字
  COME_BACK: Comeback
  
  # 每个.yml区分用的,CPU检测也用到，缓存需要用到
  DISTINGUISH: 86
  
  # .yml文件名字，这样就确保如果把代码写在AutoBuild_DiyScript.sh文件的时候，一次代码全部.yml调用都没问题
  AutoBuild_yml: AutoBuild-x86_64.yml
  

jobs:
  Compile:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Load Custom Variables
      run: |
        if [[ "${{ github.event.inputs.DEFAULT_SOURCE }}" == '大雕-lede' ]]; then
          echo "REPO_URL=https://github.com/coolsnowwolf/lede" >> $GITHUB_ENV
          echo "REPO_BRANCH=master" >> $GITHUB_ENV
          echo "WORK_DIR=DD1806${DISTINGUISH}" >> $GITHUB_ENV
          
        elif [[ "${{ github.event.inputs.DEFAULT_SOURCE }}" == '天灵-21.02' ]]; then
          echo "REPO_URL=https://github.com/immortalwrt/immortalwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=openwrt-21.02" >> $GITHUB_ENV
          echo "WORK_DIR=TL2102${DISTINGUISH}" >> $GITHUB_ENV
          
        elif [[ "${{ github.event.inputs.DEFAULT_SOURCE }}" == '天灵-18.06-k5.4' ]]; then
          echo "REPO_URL=https://github.com/immortalwrt/immortalwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=openwrt-18.06-k5.4" >> $GITHUB_ENV
          echo "WORK_DIR=TL1806K${DISTINGUISH}" >> $GITHUB_ENV
          
        elif [[ "${{ github.event.inputs.DEFAULT_SOURCE }}" == '天灵-18.06' ]]; then
          echo "REPO_URL=https://github.com/immortalwrt/immortalwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=openwrt-18.06" >> $GITHUB_ENV
          echo "WORK_DIR=TL1806${DISTINGUISH}" >> $GITHUB_ENV
          
        elif [[ "${{ github.event.inputs.DEFAULT_SOURCE }}" == '天灵-master' ]]; then
          echo "REPO_URL=https://github.com/immortalwrt/immortalwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=master" >> $GITHUB_ENV
          echo "WORK_DIR=TLMASTER${DISTINGUISH}" >> $GITHUB_ENV
          
        elif [[ "${{ github.event.inputs.DEFAULT_SOURCE }}" == 'Lienol-21.02' ]]; then
          echo "REPO_URL=https://github.com/Lienol/openwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=21.02" >> $GITHUB_ENV
          echo "WORK_DIR=LI2102${DISTINGUISH}" >> $GITHUB_ENV
          
        elif [[ "${{ github.event.inputs.DEFAULT_SOURCE }}" == 'Lienol-19.07' ]]; then
          echo "REPO_URL=https://github.com/Lienol/openwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=19.07" >> $GITHUB_ENV
          echo "WORK_DIR=LI1907${DISTINGUISH}" >> $GITHUB_ENV
          
        elif [[ "${{ github.event.inputs.DEFAULT_SOURCE }}" == 'Lienol-master' ]]; then
          echo "REPO_URL=https://github.com/Lienol/openwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=master" >> $GITHUB_ENV
          echo "WORK_DIR=LIMASTER${DISTINGUISH}" >> $GITHUB_ENV
          
        elif [[ "${{ github.event.inputs.DEFAULT_SOURCE }}" == '官方-22.03' ]]; then
          echo "REPO_URL=https://github.com/openwrt/openwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=openwrt-22.03" >> $GITHUB_ENV
          echo "WORK_DIR=GF2203${DISTINGUISH}" >> $GITHUB_ENV
          
        elif [[ "${{ github.event.inputs.DEFAULT_SOURCE }}" == '官方-21.02' ]]; then
          echo "REPO_URL=https://github.com/openwrt/openwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=openwrt-21.02" >> $GITHUB_ENV
          echo "WORK_DIR=GF2102${DISTINGUISH}" >> $GITHUB_ENV
          
        elif [[ "${{ github.event.inputs.DEFAULT_SOURCE }}" == '官方-19.07' ]]; then
          echo "REPO_URL=https://github.com/openwrt/openwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=openwrt-19.07" >> $GITHUB_ENV
          echo "WORK_DIR=GF1907${DISTINGUISH}" >> $GITHUB_ENV
          
        elif [[ "${{ github.event.inputs.DEFAULT_SOURCE }}" == '官方-master' ]]; then
          echo "REPO_URL=https://github.com/openwrt/openwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=master" >> $GITHUB_ENV
          echo "WORK_DIR=GFMASTER${DISTINGUISH}" >> $GITHUB_ENV
        fi
        
        # 上面除了区分分支跟源码链接外，还有一个WORK_DIR变量，是用来编译的时候建立文件夹用的，用来区分缓存的
        # 每个源码每个分支都一个不一样的文件夹，比如 官方的 GF + 分支 +${DISTINGUISH}来组合（GF 2102 ${DISTINGUISH}），这样确保了同样源码也不会搞错了
        # 比如说你在另外一个.yml文件还是同样的组合，然后把${DISTINGUISH}换成r2或k2啥的，这样就不会造成缓存错误了
        
        if [[ "${{ github.event.inputs.Tempoary_FLAG }}" == '高大全(Full)' ]]; then
          echo "Tempoary_FLAG=Full" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.Tempoary_FLAG }}" == '精简版(Slim)' ]]; then
          echo "Tempoary_FLAG=Slim" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.Tempoary_FLAG }}" == '养老版(Ultra)' ]]; then
          echo "Tempoary_FLAG=Ultra" >> $GITHUB_ENV
        fi
        
        # 以上我胡乱写的，主要是我看不懂你的文件，跟看天书一样，你自己按您需要搞吧
        
        if [[ -n "${{ github.event.inputs.Tempoary_IP }}" ]]; then
          echo "Tempoary_IP=${{ github.event.inputs.Tempoary_IP }}" >> $GITHUB_ENV
        fi
        
        # IP，这里不用说啥了
        
        
        echo "CONFIG_FILE=${{ github.event.inputs.Tempoary_CONFIG }}" >> $GITHUB_ENV
        echo "UPLOAD_RELEASES=${{ github.event.inputs.UPLOAD_RELEASES }}" >> $GITHUB_ENV
        echo "UPLOAD_ARTIFACTS=${{ github.event.inputs.UPLOAD_ARTIFACTS }}" >> $GITHUB_ENV
        echo "UPLOAD_BIN_ARTIFACTS=${{ github.event.inputs.UPLOAD_BIN_ARTIFACTS }}" >> $GITHUB_ENV
        echo "DELETE_USELESS_FILES=${{ github.event.inputs.DELETE_USELESS_FILES }}" >> $GITHUB_ENV
        echo "DELETE_OLD_WORKFLOW=${{ github.event.inputs.DELETE_OLD_WORKFLOW }}" >> $GITHUB_ENV
        echo "CACHE_ACCELERATE=${{ github.event.inputs.CACHE_ACCELERATE }}" >> $GITHUB_ENV
        echo "CPU_PREFERRED=${{ github.event.inputs.SKIP_E5CPU }}" >> $GITHUB_ENV
        echo "Compile_Date=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        echo "Display_Date=$(date +%Y/%m/%d)" >> $GITHUB_ENV
        
        
        if [[ -z "${{ github.event.inputs.DEFAULT_SOURCE }}" ]]; then
          echo "TIMED_TRIGGER=true" >> $GITHUB_ENV
          echo "CPU_PREFERRED=true" >> $GITHUB_ENV
        fi
        
        # TIMED_TRIGGER，如果有某个是空的，就不是手动触发编译了，要下面搞变量，要不然定时触发会没变量的
        
        # CPU_PREFERRED跳过E5的变量，有就按有的来，没有，其实就是在跳过重新编译的时候再次遇见E5，如果不是默认开启的话，就不会继续来了
        # 定时编译的时候，如果不想触发，就把CPU_PREFERRED=true改成CPU_PREFERRED=false
        
        
        ### 以上内容90%都可以写在AutoBuild_DiyScript.sh文件上的，这样就不会感觉.yml文件臃肿了

    - name: 以下为定时触发编译手动修改配置
      if: env.TIMED_TRIGGER == 'true'
      env:
        # 源码仓库链接
        REPO_URL: https://github.com/coolsnowwolf/lede
        # 源码仓库分支
        REPO_BRANCH: master
        # 配置文件名称
        CONFIG_FILE: x86_64
        # 固件标签
        Tempoary_FLAG: Full
        # 固件IP（openwrt后台地址）
        Tempoary_IP: 192.168.1.1
        # 上传固件到 releasea
        UPLOAD_RELEASES: true
        # 上传固件到 Github Artifacts
        UPLOAD_ARTIFACTS: false
        # 上传 bin 文件夹到 Github Artifacts
        UPLOAD_BIN_ARTIFACTS: false
        # 删除无用文件以增加编译空间
        DELETE_USELESS_FILES: true
        # 删除3天之前的所有Actions任务
        DELETE_OLD_WORKFLOW: false
        # Cache 加速编译
        CACHE_ACCELERATE: true
      run: |
        echo "REPO_URL=${REPO_URL}" >> $GITHUB_ENV
        echo "REPO_BRANCH=${REPO_BRANCH}" >> $GITHUB_ENV
        echo "CONFIG_FILE=${CONFIG_FILE}" >> $GITHUB_ENV
        echo "Tempoary_FLAG=${Tempoary_FLAG}" >> $GITHUB_ENV
        echo "Tempoary_IP=${Tempoary_IP}" >> $GITHUB_ENV
        echo "UPLOAD_RELEASES=${UPLOAD_RELEASES}" >> $GITHUB_ENV
        echo "UPLOAD_ARTIFACTS=${UPLOAD_ARTIFACTS}" >> $GITHUB_ENV
        echo "UPLOAD_BIN_ARTIFACTS=${UPLOAD_BIN_ARTIFACTS}" >> $GITHUB_ENV
        echo "DELETE_USELESS_FILES=${DELETE_USELESS_FILES}" >> $GITHUB_ENV
        echo "DELETE_OLD_WORKFLOW=${DELETE_OLD_WORKFLOW}" >> $GITHUB_ENV
        echo "CACHE_ACCELERATE=${CACHE_ACCELERATE}" >> $GITHUB_ENV
        echo "WORK_DIR=workdir" >> $GITHUB_ENV

    - name: Initialize Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update -y
        sudo -E apt-get -qq install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
        rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        
        # 以上抄大雕的依赖
        
        # 删除ubuntu的无用文件，使用了后，可用空间为48G左右（您以前那个删除代码，搞来搞去也就48G左右，还用不了下面的代码，用了也没反应）
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm /opt/ghc /swapfile
        
        # 再使用下面两行代码后有56G左右，一般没必要，除非编译N1固件还带打包的，就需要，主要是这个删除需要2分钟，难等，哈哈
        if [[ "${DELETE_USELESS_FILES}" == 'true' ]]; then
          docker rmi `docker images -q`
          sudo -E apt-get -qq remove -y --purge azure-cli ghc* zulu* llvm* firefox google* powershell openjdk* msodbcsql17 mongodb* moby* snapd* mysql*
        fi
        
        ### 以上内容100%都可以写在AutoBuild_DiyScript.sh文件上的
        
        # CPU检测时候如果是E5，这两行需要用到，自动触发再次编译
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        sudo -E apt-get -qq -y autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /${{ env.WORK_DIR }}
        sudo chown $USER:$GROUPS /${{ env.WORK_DIR }}
        
        # WORK_DIR变量这里有两个，还有下载源码那里有两个，注意
        
    - name: CPU检测，需要密匙，没搞秘密没用
      if: env.CPU_PREFERRED == 'true' && env.REPO_TOKEN
      run: |
        cd ${GITHUB_WORKSPACE}
        export cpu_model=`cat /proc/cpuinfo  |grep 'model name' |gawk -F : '{print $2}' | uniq -c  | sed 's/^ \+[0-9]\+ //g'`
        echo "当前CPU型号：${cpu_model}"
        if [[ `echo "${cpu_model}" |grep -Eoc "E5"` -eq '1' ]]; then
          git clone -b main https://github.com/${GIT_REPOSITORY}.git ${DISTINGUISH}
          # 如果是E5就把自己仓库下载下来
          
          export yml_path="${DISTINGUISH}/.github/workflows/${AutoBuild_yml}"
          # 然后是.yml路径写出来
          
          export PATHS1="$(grep -Eo "\- '.*'" "${yml_path}" |sed 's/^[ ]*//g' |grep -v "^#" |awk 'NR==1')"
          export PATHS2="- '${COME_BACK}/${DISTINGUISH}'"
          # 修改好触发文件，就是文件一开头那个触发，每个.yml写死也可以，就是怕人家随便改了就没效果了，所以要修改一下
          
          if [[ -n ${PATHS1} ]] && [[ -n ${PATHS2} ]]; then
            sed -i "s?${PATHS1}?${PATHS2}?g" "${yml_path}"
          else
            echo "获取变量失败,请勿胡乱修改${AutoBuild_yml}文件"
            exit 1
          fi
          # 替换好上面的变量
          
          cd ${DISTINGUISH}
          mkdir -p ${COME_BACK}
          echo "$(date +%Y%m%d%H%M%S)" > ${COME_BACK}/${DISTINGUISH}
          # 触发文件，每次有更改就触发，利用时分秒就最好了
          
          git add .
          git commit -m "Skip_E5 ${CONFIG_FILE}"
          git push --force "https://${REPO_TOKEN}@github.com/${GIT_REPOSITORY}" HEAD:main
          
          # 然后替换仓库，因为触发文件有修改，仓库就会自动再次编译了，然后下面exit 1就退出这个编译
          exit 1
        fi
        
      ### CPU检测，以上内容100%都可以写在AutoBuild_DiyScript.sh文件上的

    - name: Clone Openwrt Source Code
      working-directory: /${{ env.WORK_DIR }}
      run: |
        git clone -b $REPO_BRANCH $REPO_URL openwrt
        ln -sf /${{ env.WORK_DIR }}/openwrt $GITHUB_WORKSPACE/openwrt
        cd $GITHUB_WORKSPACE/openwrt
        ./scripts/feeds update -a
        
        # 拉取源码这里还有两个WORK_DIR变量，拉取源码后用./scripts/feeds update -a命令后，就是完整的源码了，可以对源码进行任何修改
        # 但是不要用 ./scripts/feeds install -a 这个命令，这个命令用了后会在package产生一个feeds的，就是有些东西都记录了，不过其实也没所谓吧

    - name: Run Diy Scripts
      run: |
        echo "Free space:"
        df -h
        chmod +x Scripts/AutoBuild_*.sh
        cd openwrt
        source $GITHUB_WORKSPACE/Scripts/AutoBuild_DiyScript.sh
        
        # 以上步骤完成对源码的所有修改,包括增加插件什么的,全在上面执行好,但是就是不能对 openwrt/.config 文件修改,因为这里还没产生.config文件
        # 不管是针对源码还是分支,都可以从上面第一次运行变量步骤得到的变量进行针对性投放,针对源码和分支,不管他是x86的、r2s的、还是其他也好,全部用AutoBuild_DiyScript.sh修改好
        
        cd $GITHUB_WORKSPACE/openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a > /dev/null 2>&1
        ./scripts/feeds install -a
        
        # 修改完所有东西后再次执行上面的两个命令，很需要的，为什么在下面还重复执行一次./scripts/feeds install -a，是因为有些插件缺依赖，或者有地方修改错误
        # 只执行一次./scripts/feeds install -a他不显示的，再次执行就出来了
        
        
        rm -f .config && cp $GITHUB_WORKSPACE/Configs/$CONFIG_FILE .config
        
        #if [ "${{ env.CACHE_ACCELERATE }}" == true ]
        #then
        #    echo -e "\nCONFIG_DEVEL=y\nCONFIG_CCACHE=y\n" >> $GITHUB_WORKSPACE/openwrt/.config
        #fi
        # 这个好像没用，我没用过，不了解什么情况
        
        # 以下步骤可以对 openwrt/.config 写入您想要写入的内容,就是别对源码进行任何修改了,也不要增加插件啥的,这个zzz-default-settings文件倒是可以改
        # 还有就是针对.config机型，制作出在线更新的文件,老大您现在的文件名叫啥我看不懂您变量了,以前就是放etc叫openwrt_info
        # 在这里还可以针对机型对OpenClash或者AdGuardHome增加内核的
        
        make defconfig
        echo "TARGET_BOARD=$(awk -F '[="]+' '/TARGET_BOARD/{print $2}' .config)" >> ${GITHUB_ENV}
        
        # 执行make defconfig才能搞出TARGET_BOARD，因为下面缓存需要用到
        
        source $GITHUB_WORKSPACE/Scripts/AutoBuild_Function.sh
        Firmware_Diy_Before
        Firmware_Diy_Main
        Firmware_Diy
        Firmware_Diy_Other
        
    - name: Accelerate
      if: github.event.inputs.CACHE_ACCELERATE == 'true'
      uses: stupidloud/cachewrtbuild@main
      with:
        ccache: 'true'
        mixkey: "${{ env.TARGET_BOARD }}"
        prefix: ${{ github.workspace }}/openwrt
        
      # mixkey也挺有用的，防止那些蛋痛的人乱搞，比如我现在编译X86有缓存了，还继续用这个.yml编译，在配置文件里面改了机型，如果没mixkey区分的话，编译就错误了，因为缓存不对
      # 其实也防止同源码多机型编译造成的缓存错误问题

    - name: Pre-download Libraries
      run: |
        cd openwrt
        make defconfig
        make download -j8

    - name: Build OpenWrt
      id: compile
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s

    - name: Checkout Firmware
      if: steps.compile.outcome == 'success' && !cancelled()
      run: |
        cd openwrt
        source $GITHUB_WORKSPACE/Scripts/AutoBuild_Function.sh
        Firmware_Diy_End

    - name: Upload Firmware to Artifacts
      uses: actions/upload-artifact@main
      if: env.UPLOAD_ARTIFACTS == 'true' && steps.compile.outcome == 'success' && !cancelled()
      with:
        name: ${{ env.CONFIG_FILE }}_firmware_${{ env.Compile_Date }}
        path: openwrt/bin/Firmware

    - name: Upload bin to Artifacts
      uses: actions/upload-artifact@main
      if: env.UPLOAD_BIN_ARTIFACTS == 'true' && steps.compile.outcome == 'success' && !cancelled()
      with:
        name: ${{ env.CONFIG_FILE }}_bin_${{ env.Compile_Date }}
        path: openwrt/bin

    - name: Upload Firmware to Release
      if: env.UPLOAD_RELEASES == 'true' && steps.compile.outcome == 'success' && !cancelled()
      uses: ncipollo/release-action@main
      with:
        name: AutoUpdate
        tag: AutoUpdate
        token: ${{ secrets.REPO_TOKEN }}
        artifacts: openwrt/bin/Firmware/*
        allowUpdates: true
        
    - name: Download Github API
      if: env.UPLOAD_RELEASES == 'true' && steps.compile.outcome == 'success' && !cancelled()
      run: |
        wget https://api.github.com/repos/${{github.repository}}/releases/tags/AutoUpdate -O API

    - name: Upload API to Github Release 
      if: env.UPLOAD_RELEASES == 'true' && steps.compile.outcome == 'success' && !cancelled()
      uses: ncipollo/release-action@main
      with:
        name: AutoUpdate
        tag: AutoUpdate
        token: ${{ secrets.REPO_TOKEN }}
        artifacts: ./API
        allowUpdates: true

    - name: Delete old Workflow Runs
      continue-on-error: true
      if: env.DELETE_OLD_WORKFLOW == 'true' && !cancelled()
      uses: Mattraks/delete-workflow-runs@v2
      with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 0
