###########################################################
#   Description: Refresh Release API                      #
#   Author: Hyy2001X                                      #
###########################################################

name: Refresh API

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      refresh_switch:
        description: '手动刷新 API'
        default: 'true'

  schedule:
    - cron: 0 4,16 * * *

jobs:
  Job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Download Github Release API
      run: |
        wget https://api.github.com/repos/${{github.repository}}/releases/tags/AutoUpdate -O API
        
    - name: Upload API to Github Release 
      uses: ncipollo/release-action@main
      with:
        name: AutoUpdate
        tag: AutoUpdate
        token: ${{ secrets.REPO_TOKEN }}
        artifacts: ./API
        allowUpdates: true
